### ISSUE TITLE
gsoc about caching

### ISSUE THREAD

**Issue by tdhock** [Anirban166/Autocomment-atime-results#40]
hi @Anirban166 can you add a project to https://github.com/rstats-gsoc/gsoc2025/wiki/table-of-proposed-coding-projects
about implemting this https://github.com/Rdatatable/data.table/issues/6528

**Comment by Anirban166** [comment]
@tdhock I wrote [this wiki page](https://github.com/rstats-gsoc/gsoc2025/wiki/Optimizing-a-performance-testing-workflow-by-reusing-minified-R-package-versions-between-CI-runs), which I think pretty much covers every section of the project template but let me know if I forgot something essential. I tried to segment the steps for the optimization and made the tests accordingly. I wrote in as much detail I could provide for the information I had on the GHA-end of things to implement, but there is not much on the `atime` side, which you can add now (also, I assigned it 175 hours on the table since I don't think its enough for 350 with the current scope) 

Let me know your thoughts!

**Comment by tdhock** [comment]
looks excellent thanks!
